### ISSUE TITLE
Seeker (Sorcerer) not compatible with Sage Sorcerer

### ISSUE THREAD

**Issue by fnzr** [Vek17/WrathMods-MultipleArchetypes#1]
Using the latest release of the mod (v1.0.0).
As far as I can tell, Sage Sorcerer should be compatible with Seeker Sorcerer.
It probably doesn't work because for some reason, Seeker removes the Bloodline and adds it back again as an archetype feature (I can't say if there's any actual change)
How can I workaround this situation?

**Comment by Vek17** [comment]
Seeker modifies bloodlines and uses a different set of bloodlines, Sage sorcerer replaces the bloodline selection with a mutated bloodline. These both replace the bloodline feature and are thus not compatible. Technically these are arguably compatible in tabletop but given how they have to be implemented in game they are not.

**Comment by fnzr** [comment]
Oh I see, I hadn't noticed that.
Thanks.
